import jsPDF from "jspdf";
import "jspdf-autotable";

interface PdfData {
  diseaseName: string;
  confidence: number;
  healthScore: number;
  severity: string;
  affectedArea: number;
  description: string;
  treatments: { step: number; label: string; explanation: string }[];
  medicines: { name: string; purpose: string; price: string }[];
  preventions: string[];
  weather?: { temp: number; humidity: number; rain_probability: number; location: string };
  costEstimate?: { fungicide: number; nutrients: number; pesticides: number; total: number };
  scanImage?: string;
}

export const generatePdfReport = async (data: PdfData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(34, 120, 60);
  doc.text("AgroLens AI - Plant Health Report", pageWidth / 2, y, { align: "center" });
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: "center" });
  y += 12;

  // Leaf image
  if (data.scanImage) {
    try {
      doc.addImage(data.scanImage, "JPEG", 15, y, 60, 45);
      y += 50;
    } catch {
      y += 5;
    }
  }

  // Disease Result
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("Disease Detected", 15, y);
  y += 7;

  doc.setFontSize(11);
  doc.text(`Disease: ${data.diseaseName}`, 15, y); y += 6;
  doc.text(`Confidence: ${data.confidence}%`, 15, y); y += 6;
  doc.text(`Health Score: ${data.healthScore}/100`, 15, y); y += 6;
  doc.text(`Severity: ${data.severity}`, 15, y); y += 6;
  doc.text(`Affected Area: ${data.affectedArea}%`, 15, y); y += 10;

  // Description
  doc.setFontSize(14);
  doc.text("Description", 15, y); y += 7;
  doc.setFontSize(10);
  const descLines = doc.splitTextToSize(data.description, pageWidth - 30);
  doc.text(descLines, 15, y);
  y += descLines.length * 5 + 8;

  // Weather
  if (data.weather) {
    doc.setFontSize(14);
    doc.text("Weather Conditions", 15, y); y += 7;
    doc.setFontSize(10);
    doc.text(`Location: ${data.weather.location}`, 15, y); y += 5;
    doc.text(`Temperature: ${data.weather.temp}°C`, 15, y); y += 5;
    doc.text(`Humidity: ${data.weather.humidity}%`, 15, y); y += 5;
    doc.text(`Rain Probability: ${data.weather.rain_probability}%`, 15, y); y += 10;
  }

  // Treatment Plan
  if (y > 240) { doc.addPage(); y = 15; }
  doc.setFontSize(14);
  doc.text("Treatment Plan", 15, y); y += 7;
  doc.setFontSize(10);
  data.treatments.forEach((t) => {
    if (y > 270) { doc.addPage(); y = 15; }
    doc.setFont("helvetica", "bold");
    doc.text(`Step ${t.step}: ${t.label}`, 15, y); y += 5;
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(t.explanation, pageWidth - 30);
    doc.text(lines, 15, y);
    y += lines.length * 5 + 3;
  });
  y += 5;

  // Medicines
  if (y > 240) { doc.addPage(); y = 15; }
  doc.setFontSize(14);
  doc.text("Recommended Medicines", 15, y); y += 7;
  doc.setFontSize(10);
  data.medicines.forEach((m) => {
    if (y > 270) { doc.addPage(); y = 15; }
    doc.text(`• ${m.name} - ${m.purpose} (${m.price})`, 15, y); y += 6;
  });
  y += 5;

  // Prevention
  if (y > 250) { doc.addPage(); y = 15; }
  doc.setFontSize(14);
  doc.text("Prevention Tips", 15, y); y += 7;
  doc.setFontSize(10);
  data.preventions.forEach((p) => {
    doc.text(`• ${p}`, 15, y); y += 5;
  });
  y += 5;

  // Cost Estimate
  if (data.costEstimate) {
    if (y > 240) { doc.addPage(); y = 15; }
    doc.setFontSize(14);
    doc.text("Treatment Cost Estimate", 15, y); y += 7;
    doc.setFontSize(10);
    doc.text(`Fungicide: ₹${data.costEstimate.fungicide.toLocaleString("en-IN")}`, 15, y); y += 5;
    doc.text(`Nutrients: ₹${data.costEstimate.nutrients.toLocaleString("en-IN")}`, 15, y); y += 5;
    doc.text(`Pesticides: ₹${data.costEstimate.pesticides.toLocaleString("en-IN")}`, 15, y); y += 5;
    doc.setFont("helvetica", "bold");
    doc.text(`Total: ₹${data.costEstimate.total.toLocaleString("en-IN")}`, 15, y); y += 5;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by AgroLens AI - AI-Powered Plant Disease Detection", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

  doc.save(`AgroLens-Report-${data.diseaseName.replace(/\s/g, "-")}-${new Date().toISOString().slice(0, 10)}.pdf`);
};
