export interface Language {
  code: string;
  label: string;
  speechCode: string;
}

export const languages: Language[] = [
  { code: "en", label: "English", speechCode: "en-US" },
  { code: "hi", label: "हिन्दी (Hindi)", speechCode: "hi-IN" },
  { code: "te", label: "తెలుగు (Telugu)", speechCode: "te-IN" },
  { code: "ta", label: "தமிழ் (Tamil)", speechCode: "ta-IN" },
  { code: "kn", label: "ಕನ್ನಡ (Kannada)", speechCode: "kn-IN" },
  { code: "mr", label: "मराठी (Marathi)", speechCode: "mr-IN" },
  { code: "bn", label: "বাংলা (Bengali)", speechCode: "bn-IN" },
];

export const translations: Record<string, Record<string, string>> = {
  en: {
    analysisResults: "Analysis Results",
    detailedReport: "Detailed plant health report",
    diseaseDetected: "Disease Detected",
    confidence: "Confidence",
    severity: "Severity",
    affectedArea: "Affected Area",
    healthScore: "Plant Health Score",
    description: "Description",
    causes: "Causes",
    treatment: "Treatment",
    medicine: "Medicine",
    prevention: "Prevention",
    costEstimator: "Cost Estimator",
    weather: "Weather & Risk",
    downloadPdf: "Download PDF Report",
    voiceAsk: "Ask by Voice",
    voiceListen: "Listen to Advice",
    stopVoice: "Stop",
    speakingAdvice: "Speaking…",
    listeningVoice: "Listening…",
    youSaid: "You said:",
    fungalInfection: "Fungal Infection",
    excessMoisture: "Excess Moisture",
    poorSoilNutrients: "Poor Soil Nutrients",
    pestDamage: "Pest Damage",
    removeInfectedLeaves: "Remove infected leaves",
    removeExplanation: "Removing infected leaves prevents the fungus from spreading to healthy parts of the plant.",
    applyFungicide: "Apply fungicide spray",
    fungicideExplanation: "Fungicide spray creates a protective barrier and kills existing fungal spores on the leaves.",
    improveAirCirculation: "Improve air circulation",
    airExplanation: "Better air flow reduces moisture buildup which slows fungal growth and prevents new infections.",
    reduceOverwatering: "Reduce overwatering",
    waterExplanation: "Excess water creates humid conditions that favor fungal diseases. Water at the base, not on leaves.",
    properIrrigation: "Proper irrigation",
    cropRotation: "Crop rotation",
    soilTesting: "Soil testing",
    regularInspection: "Regular inspection",
    farmSize: "Farm Size (acres)",
    cropType: "Crop Type",
    estimateCost: "Estimate Cost",
    fungicide: "Fungicide",
    nutrients: "Nutrient Supplements",
    pesticides: "Pesticides",
    totalCost: "Total Estimated Cost",
    costNote: "Cost is estimated based on average market prices and the amount of treatment required per acre.",
    lowRisk: "Low Risk",
    moderateRisk: "Moderate Risk",
    highRisk: "High Risk",
    healthy: "Healthy",
    mildInfection: "Mild Infection",
    moderateInfection: "Moderate Infection",
    severeInfection: "Severe Infection",
    diseaseDescription: "Early blight is a fungal disease that affects tomato leaves, causing dark spots and leaf decay. It usually occurs in warm and humid conditions and can spread rapidly if untreated.",
    weatherRiskMsg: "Current weather conditions may affect disease progression. Monitor humidity and temperature closely.",
    // Navbar
    scan: "Scan",
    history: "History",
    plantGuide: "Plant Guide",
    about: "About",
    language: "Language",
    // Plant Guide
    cropEncyclopedia: "Crop Encyclopedia",
    browsecrops: "Browse crops and their common diseases",
    searchCrops: "Search crops...",
    allCrops: "All Crops",
    vegetables: "Vegetables",
    fruits: "Fruits",
    grains: "Grains",
    knownDiseases: "known diseases",
    commonDiseases: "Common Diseases",
    symptoms: "Symptoms",
    preventiveActions: "Preventive Actions",
    weatherRiskPredictor: "Weather Risk Predictor",
    predictRisk: "Predict Risk",
    diseaseRisk: "Disease Risk",
  },
  hi: {
    analysisResults: "विश्लेषण परिणाम",
    detailedReport: "विस्तृत पौधे स्वास्थ्य रिपोर्ट",
    diseaseDetected: "रोग का पता चला",
    confidence: "विश्वसनीयता",
    severity: "गंभीरता",
    affectedArea: "प्रभावित क्षेत्र",
    healthScore: "पौधे का स्वास्थ्य स्कोर",
    description: "विवरण",
    causes: "कारण",
    treatment: "उपचार",
    medicine: "दवाई",
    prevention: "रोकथाम",
    costEstimator: "लागत अनुमानक",
    weather: "मौसम और जोखिम",
    downloadPdf: "PDF रिपोर्ट डाउनलोड करें",
    voiceAsk: "आवाज से पूछें",
    voiceListen: "सलाह सुनें",
    stopVoice: "रुकें",
    speakingAdvice: "बोल रहा है…",
    listeningVoice: "सुन रहा है…",
    youSaid: "आपने कहा:",
    fungalInfection: "कवक संक्रमण",
    excessMoisture: "अधिक नमी",
    poorSoilNutrients: "खराब मिट्टी पोषक तत्व",
    pestDamage: "कीट क्षति",
    removeInfectedLeaves: "संक्रमित पत्तियां हटाएं",
    removeExplanation: "संक्रमित पत्तियों को हटाने से कवक को पौधे के स्वस्थ भागों में फैलने से रोकता है।",
    applyFungicide: "कवकनाशी स्प्रे लगाएं",
    fungicideExplanation: "कवकनाशी स्प्रे एक सुरक्षात्मक बाधा बनाता है और पत्तियों पर मौजूद कवक बीजाणुओं को मारता है।",
    improveAirCirculation: "हवा का संचार बढ़ाएं",
    airExplanation: "बेहतर हवा का प्रवाह नमी को कम करता है जो कवक के विकास को धीमा करता है।",
    reduceOverwatering: "अधिक पानी देना कम करें",
    waterExplanation: "अतिरिक्त पानी नम स्थिति बनाता है जो कवक रोगों को बढ़ावा देता है।",
    properIrrigation: "उचित सिंचाई",
    cropRotation: "फसल चक्र",
    soilTesting: "मिट्टी परीक्षण",
    regularInspection: "नियमित निरीक्षण",
    farmSize: "खेत का आकार (एकड़)",
    cropType: "फसल का प्रकार",
    estimateCost: "लागत अनुमान",
    fungicide: "कवकनाशी",
    nutrients: "पोषक तत्व पूरक",
    pesticides: "कीटनाशक",
    totalCost: "कुल अनुमानित लागत",
    costNote: "लागत का अनुमान औसत बाजार कीमतों और प्रति एकड़ उपचार की मात्रा के आधार पर लगाया गया है।",
    lowRisk: "कम जोखिम",
    moderateRisk: "मध्यम जोखिम",
    highRisk: "उच्च जोखिम",
    healthy: "स्वस्थ",
    mildInfection: "हल्का संक्रमण",
    moderateInfection: "मध्यम संक्रमण",
    severeInfection: "गंभीर संक्रमण",
    diseaseDescription: "अगेती अंगमारी एक कवक रोग है जो टमाटर की पत्तियों को प्रभावित करता है, जिससे काले धब्बे और पत्ती सड़ जाती है। यह आमतौर पर गर्म और नम स्थितियों में होता है।",
    weatherRiskMsg: "वर्तमान मौसम की स्थिति रोग की प्रगति को प्रभावित कर सकती है। आर्द्रता और तापमान की बारीकी से निगरानी करें।",
    scan: "स्कैन",
    history: "इतिहास",
    plantGuide: "पौधे की गाइड",
    about: "जानकारी",
    language: "भाषा",
    cropEncyclopedia: "फसल विश्वकोश",
    browsecrops: "फसलों और उनके सामान्य रोगों को ब्राउज़ करें",
    searchCrops: "फसलें खोजें...",
    allCrops: "सभी फसलें",
    vegetables: "सब्जियां",
    fruits: "फल",
    grains: "अनाज",
    knownDiseases: "ज्ञात रोग",
    commonDiseases: "सामान्य रोग",
    symptoms: "लक्षण",
    preventiveActions: "निवारक कार्य",
    weatherRiskPredictor: "मौसम जोखिम भविष्यवक्ता",
    predictRisk: "जोखिम का अनुमान",
    diseaseRisk: "रोग जोखिम",
  },
  te: {
    analysisResults: "విశ్లేషణ ఫలితాలు",
    detailedReport: "వివరమైన మొక్క ఆరోగ్య నివేదిక",
    diseaseDetected: "వ్యాధి గుర్తించబడింది",
    confidence: "విశ్వాసం",
    severity: "తీవ్రత",
    affectedArea: "ప్రభావిత ప్రాంతం",
    healthScore: "మొక్క ఆరోగ్య స్కోరు",
    description: "వివరణ",
    causes: "కారణాలు",
    treatment: "చికిత్స",
    medicine: "ఔషధం",
    prevention: "నివారణ",
    costEstimator: "ఖర్చు అంచనా",
    weather: "వాతావరణం & ప్రమాదం",
    downloadPdf: "PDF నివేదిక డౌన్‌లోడ్",
    voiceAsk: "వాయిస్ ద్వారా అడగండి",
    voiceListen: "సలహా వినండి",
    stopVoice: "ఆపండి",
    speakingAdvice: "చెబుతోంది…",
    listeningVoice: "వింటోంది…",
    youSaid: "మీరు అన్నారు:",
    fungalInfection: "ఫంగల్ ఇన్ఫెక్షన్",
    excessMoisture: "అధిక తేమ",
    poorSoilNutrients: "పేలవమైన నేల పోషకాలు",
    pestDamage: "పురుగు నష్టం",
    removeInfectedLeaves: "సంక్రమించిన ఆకులను తొలగించండి",
    removeExplanation: "సంక్రమించిన ఆకులను తొలగించడం వల్ల ఫంగస్ వ్యాపించకుండా ఉంటుంది.",
    applyFungicide: "ఫంగిసైడ్ స్ప్రే అప్లై చేయండి",
    fungicideExplanation: "ఫంగిసైడ్ స్ప్రే రక్షణ అవరోధాన్ని సృష్టిస్తుంది.",
    improveAirCirculation: "గాలి ప్రసరణ మెరుగుపరచండి",
    airExplanation: "మంచి గాలి ప్రవాహం తేమను తగ్గిస్తుంది.",
    reduceOverwatering: "అధిక నీరు పోయడం తగ్గించండి",
    waterExplanation: "అధిక నీరు తేమ పరిస్థితులను సృష్టిస్తుంది.",
    properIrrigation: "సరైన సాగునీరు",
    cropRotation: "పంట మార్పిడి",
    soilTesting: "నేల పరీక్ష",
    regularInspection: "క్రమ తనిఖీ",
    farmSize: "పొలం పరిమాణం (ఎకరాలు)",
    cropType: "పంట రకం",
    estimateCost: "ఖర్చు అంచనా",
    fungicide: "ఫంగిసైడ్",
    nutrients: "పోషక పదార్థాలు",
    pesticides: "పురుగుమందులు",
    totalCost: "మొత్తం అంచనా ఖర్చు",
    costNote: "ఖర్చు సగటు మార్కెట్ ధరల ఆధారంగా అంచనా వేయబడింది.",
    lowRisk: "తక్కువ ప్రమాదం",
    moderateRisk: "మధ్యస్థ ప్రమాదం",
    highRisk: "అధిక ప్రమాదం",
    healthy: "ఆరోగ్యకరమైన",
    mildInfection: "తేలికపాటి సంక్రమణ",
    moderateInfection: "మధ్యస్థ సంక్రమణ",
    severeInfection: "తీవ్రమైన సంక్రమణ",
    diseaseDescription: "అగేటి అంగమారి టమాటా ఆకులను ప్రభావితం చేసే ఫంగల్ వ్యాధి.",
    weatherRiskMsg: "ప్రస్తుత వాతావరణ పరిస్థితులు వ్యాధి ప్రగతిని ప్రభావితం చేయవచ్చు.",
    scan: "స్కాన్",
    history: "చరిత్ర",
    plantGuide: "మొక్కల గైడ్",
    about: "గురించి",
    language: "భాష",
    cropEncyclopedia: "పంట విజ్ఞానకోశం",
    browsecrops: "పంటలు మరియు వాటి సాధారణ వ్యాధులను బ్రౌజ్ చేయండి",
    searchCrops: "పంటలను శోధించండి...",
    allCrops: "అన్ని పంటలు",
    vegetables: "కూరగాయలు",
    fruits: "పండ్లు",
    grains: "ధాన్యాలు",
    knownDiseases: "తెలిసిన వ్యాధులు",
    commonDiseases: "సాధారణ వ్యాధులు",
    symptoms: "లక్షణాలు",
    preventiveActions: "నివారణ చర్యలు",
    weatherRiskPredictor: "వాతావరణ ప్రమాద అంచనా",
    predictRisk: "ప్రమాదాన్ని అంచనా వేయండి",
    diseaseRisk: "వ్యాధి ప్రమాదం",
  },
  ta: {
    analysisResults: "பகுப்பாய்வு முடிவுகள்",
    detailedReport: "விரிவான தாவர ஆரோக்கிய அறிக்கை",
    diseaseDetected: "நோய் கண்டறியப்பட்டது",
    confidence: "நம்பகத்தன்மை",
    severity: "தீவிரம்",
    affectedArea: "பாதிக்கப்பட்ட பகுதி",
    healthScore: "தாவர ஆரோக்கிய மதிப்பெண்",
    description: "விளக்கம்",
    causes: "காரணங்கள்",
    treatment: "சிகிச்சை",
    medicine: "மருந்து",
    prevention: "தடுப்பு",
    costEstimator: "செலவு மதிப்பீடு",
    weather: "வானிலை & ஆபத்து",
    downloadPdf: "PDF அறிக்கை பதிவிறக்கம்",
    voiceAsk: "குரலில் கேளுங்கள்",
    voiceListen: "ஆலோசனை கேளுங்கள்",
    stopVoice: "நிறுத்து",
    speakingAdvice: "பேசுகிறது…",
    listeningVoice: "கேட்கிறது…",
    youSaid: "நீங்கள் சொன்னது:",
    fungalInfection: "பூஞ்சை நோய்",
    excessMoisture: "அதிக ஈரப்பதம்",
    poorSoilNutrients: "மோசமான மண் ஊட்டச்சத்துக்கள்",
    pestDamage: "பூச்சி சேதம்",
    removeInfectedLeaves: "நோயுற்ற இலைகளை அகற்றுங்கள்",
    removeExplanation: "நோயுற்ற இலைகளை அகற்றுவது பூஞ்சை பரவுவதைத் தடுக்கிறது.",
    applyFungicide: "பூஞ்சைக்கொல்லி தெளிக்கவும்",
    fungicideExplanation: "பூஞ்சைக்கொல்லி தெளிப்பு பாதுகாப்பு தடையை உருவாக்குகிறது.",
    improveAirCirculation: "காற்றோட்டத்தை மேம்படுத்தவும்",
    airExplanation: "சிறந்த காற்றோட்டம் ஈரப்பதத்தைக் குறைக்கிறது.",
    reduceOverwatering: "அதிக நீர்ப்பாசனத்தைக் குறைக்கவும்",
    waterExplanation: "அதிக நீர் ஈரமான நிலைகளை உருவாக்குகிறது.",
    properIrrigation: "சரியான நீர்ப்பாசனம்",
    cropRotation: "பயிர் சுழற்சி",
    soilTesting: "மண் பரிசோதனை",
    regularInspection: "வழக்கமான ஆய்வு",
    farmSize: "பண்ணை அளவு (ஏக்கர்)",
    cropType: "பயிர் வகை",
    estimateCost: "செலவு மதிப்பீடு",
    fungicide: "பூஞ்சைக்கொல்லி",
    nutrients: "ஊட்டச்சத்து கூடுதல்கள்",
    pesticides: "பூச்சிக்கொல்லிகள்",
    totalCost: "மொத்த மதிப்பிடப்பட்ட செலவு",
    costNote: "சராசரி சந்தை விலைகளின் அடிப்படையில் செலவு மதிப்பிடப்படுகிறது.",
    lowRisk: "குறைந்த ஆபத்து",
    moderateRisk: "மிதமான ஆபத்து",
    highRisk: "அதிக ஆபத்து",
    healthy: "ஆரோக்கியமான",
    mildInfection: "லேசான தொற்று",
    moderateInfection: "மிதமான தொற்று",
    severeInfection: "கடுமையான தொற்று",
    diseaseDescription: "ஆரம்பகால அழுகல் தக்காளி இலைகளை பாதிக்கும் பூஞ்சை நோயாகும்.",
    weatherRiskMsg: "தற்போதைய வானிலை நோய் முன்னேற்றத்தை பாதிக்கலாம்.",
    scan: "ஸ்கேன்",
    history: "வரலாறு",
    plantGuide: "தாவர வழிகாட்டி",
    about: "பற்றி",
    language: "மொழி",
    cropEncyclopedia: "பயிர் கலைக்களஞ்சியம்",
    browsecrops: "பயிர்கள் மற்றும் அவற்றின் நோய்களை உலாவுங்கள்",
    searchCrops: "பயிர்களைத் தேடுங்கள்...",
    allCrops: "அனைத்து பயிர்கள்",
    vegetables: "காய்கறிகள்",
    fruits: "பழங்கள்",
    grains: "தானியங்கள்",
    knownDiseases: "அறியப்பட்ட நோய்கள்",
    commonDiseases: "பொதுவான நோய்கள்",
    symptoms: "அறிகுறிகள்",
    preventiveActions: "தடுப்பு நடவடிக்கைகள்",
    weatherRiskPredictor: "வானிலை ஆபத்து கணிப்பான்",
    predictRisk: "ஆபத்தை கணிக்கவும்",
    diseaseRisk: "நோய் ஆபத்து",
  },
  kn: {
    analysisResults: "ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳು",
    detailedReport: "ವಿವರವಾದ ಸಸ್ಯ ಆರೋಗ್ಯ ವರದಿ",
    diseaseDetected: "ರೋಗ ಪತ್ತೆಯಾಗಿದೆ",
    confidence: "ವಿಶ್ವಾಸ",
    severity: "ತೀವ್ರತೆ",
    affectedArea: "ಪೀಡಿತ ಪ್ರದೇಶ",
    healthScore: "ಸಸ್ಯ ಆರೋಗ್ಯ ಅಂಕ",
    description: "ವಿವರಣೆ",
    causes: "ಕಾರಣಗಳು",
    treatment: "ಚಿಕಿತ್ಸೆ",
    medicine: "ಔಷಧ",
    prevention: "ತಡೆಗಟ್ಟುವಿಕೆ",
    costEstimator: "ವೆಚ್ಚ ಅಂದಾಜು",
    weather: "ಹವಾಮಾನ & ಅಪಾಯ",
    downloadPdf: "PDF ವರದಿ ಡೌನ್‌ಲೋಡ್",
    voiceAsk: "ಧ್ವನಿ ಮೂಲಕ ಕೇಳಿ",
    voiceListen: "ಸಲಹೆ ಕೇಳಿ",
    stopVoice: "ನಿಲ್ಲಿಸಿ",
    speakingAdvice: "ಮಾತನಾಡುತ್ತಿದೆ…",
    listeningVoice: "ಕೇಳುತ್ತಿದೆ…",
    youSaid: "ನೀವು ಹೇಳಿದ್ದು:",
    fungalInfection: "ಶಿಲೀಂಧ್ರ ಸೋಂಕು",
    excessMoisture: "ಹೆಚ್ಚಿನ ತೇವಾಂಶ",
    poorSoilNutrients: "ಕಳಪೆ ಮಣ್ಣಿನ ಪೋಷಕಾಂಶಗಳು",
    pestDamage: "ಕೀಟ ಹಾನಿ",
    removeInfectedLeaves: "ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ",
    removeExplanation: "ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕುವುದು ಶಿಲೀಂಧ್ರ ಹರಡುವುದನ್ನು ತಡೆಯುತ್ತದೆ.",
    applyFungicide: "ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ",
    fungicideExplanation: "ಶಿಲೀಂಧ್ರನಾಶಕ ರಕ್ಷಣಾತ್ಮಕ ಅಡೆತಡೆಯನ್ನು ಸೃಷ್ಟಿಸುತ್ತದೆ.",
    improveAirCirculation: "ಗಾಳಿ ಪ್ರಸರಣ ಸುಧಾರಿಸಿ",
    airExplanation: "ಉತ್ತಮ ಗಾಳಿ ಹರಿವು ತೇವಾಂಶವನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.",
    reduceOverwatering: "ಹೆಚ್ಚು ನೀರುಹಾಕುವುದನ್ನು ಕಡಿಮೆ ಮಾಡಿ",
    waterExplanation: "ಹೆಚ್ಚಿನ ನೀರು ತೇವಾಂಶ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಸೃಷ್ಟಿಸುತ್ತದೆ.",
    properIrrigation: "ಸರಿಯಾದ ನೀರಾವರಿ",
    cropRotation: "ಬೆಳೆ ಸರದಿ",
    soilTesting: "ಮಣ್ಣು ಪರೀಕ್ಷೆ",
    regularInspection: "ನಿಯಮಿತ ತಪಾಸಣೆ",
    farmSize: "ಹೊಲದ ಗಾತ್ರ (ಎಕರೆ)",
    cropType: "ಬೆಳೆ ಪ್ರಕಾರ",
    estimateCost: "ವೆಚ್ಚ ಅಂದಾಜು",
    fungicide: "ಶಿಲೀಂಧ್ರನಾಶಕ",
    nutrients: "ಪೋಷಕಾಂಶ ಪೂರಕಗಳು",
    pesticides: "ಕೀಟನಾಶಕಗಳು",
    totalCost: "ಒಟ್ಟು ಅಂದಾಜು ವೆಚ್ಚ",
    costNote: "ಸರಾಸರಿ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳ ಆಧಾರದ ಮೇಲೆ ವೆಚ್ಚ ಅಂದಾಜು ಮಾಡಲಾಗಿದೆ.",
    lowRisk: "ಕಡಿಮೆ ಅಪಾಯ",
    moderateRisk: "ಮಧ್ಯಮ ಅಪಾಯ",
    highRisk: "ಹೆಚ್ಚಿನ ಅಪಾಯ",
    healthy: "ಆರೋಗ್ಯಕರ",
    mildInfection: "ಸೌಮ್ಯ ಸೋಂಕು",
    moderateInfection: "ಮಧ್ಯಮ ಸೋಂಕು",
    severeInfection: "ತೀವ್ರ ಸೋಂಕು",
    diseaseDescription: "ಆರಂಭಿಕ ಅಂಗಮಾರಿ ಟೊಮೆಟೊ ಎಲೆಗಳ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುವ ಶಿಲೀಂಧ್ರ ರೋಗ.",
    weatherRiskMsg: "ಪ್ರಸ್ತುತ ಹವಾಮಾನ ರೋಗ ಪ್ರಗತಿಯ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರಬಹುದು.",
    scan: "ಸ್ಕ್ಯಾನ್",
    history: "ಇತಿಹಾಸ",
    plantGuide: "ಸಸ್ಯ ಮಾರ್ಗದರ್ಶಿ",
    about: "ಬಗ್ಗೆ",
    language: "ಭಾಷೆ",
    cropEncyclopedia: "ಬೆಳೆ ವಿಶ್ವಕೋಶ",
    browsecrops: "ಬೆಳೆಗಳು ಮತ್ತು ಅವುಗಳ ರೋಗಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
    searchCrops: "ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ...",
    allCrops: "ಎಲ್ಲಾ ಬೆಳೆಗಳು",
    vegetables: "ತರಕಾರಿಗಳು",
    fruits: "ಹಣ್ಣುಗಳು",
    grains: "ಧಾನ್ಯಗಳು",
    knownDiseases: "ತಿಳಿದ ರೋಗಗಳು",
    commonDiseases: "ಸಾಮಾನ್ಯ ರೋಗಗಳು",
    symptoms: "ಲಕ್ಷಣಗಳು",
    preventiveActions: "ತಡೆಗಟ್ಟುವ ಕ್ರಮಗಳು",
    weatherRiskPredictor: "ಹವಾಮಾನ ಅಪಾಯ ಮುನ್ಸೂಚನೆ",
    predictRisk: "ಅಪಾಯವನ್ನು ಊಹಿಸಿ",
    diseaseRisk: "ರೋಗ ಅಪಾಯ",
  },
  mr: {
    analysisResults: "विश्लेषण निकाल",
    detailedReport: "तपशीलवार वनस्पती आरोग्य अहवाल",
    diseaseDetected: "रोग आढळला",
    confidence: "विश्वसनीयता",
    severity: "तीव्रता",
    affectedArea: "प्रभावित क्षेत्र",
    healthScore: "वनस्पती आरोग्य गुण",
    description: "वर्णन",
    causes: "कारणे",
    treatment: "उपचार",
    medicine: "औषध",
    prevention: "प्रतिबंध",
    costEstimator: "खर्च अंदाजक",
    weather: "हवामान आणि धोका",
    downloadPdf: "PDF अहवाल डाउनलोड करा",
    voiceAsk: "आवाजाने विचारा",
    voiceListen: "सल्ला ऐका",
    stopVoice: "थांबा",
    speakingAdvice: "बोलत आहे…",
    listeningVoice: "ऐकत आहे…",
    youSaid: "तुम्ही म्हणालात:",
    fungalInfection: "बुरशी संसर्ग",
    excessMoisture: "अतिरिक्त ओलावा",
    poorSoilNutrients: "खराब मातीची पोषक तत्वे",
    pestDamage: "कीटक नुकसान",
    removeInfectedLeaves: "संक्रमित पाने काढा",
    removeExplanation: "संक्रमित पाने काढल्याने बुरशीचा प्रसार रोखता येतो.",
    applyFungicide: "बुरशीनाशक फवारणी करा",
    fungicideExplanation: "बुरशीनाशक फवारणी संरक्षणात्मक अडथळा निर्माण करते.",
    improveAirCirculation: "हवा खेळती करा",
    airExplanation: "चांगला वायु प्रवाह ओलावा कमी करतो.",
    reduceOverwatering: "जास्त पाणी देणे कमी करा",
    waterExplanation: "जास्त पाणी ओलसर परिस्थिती निर्माण करते.",
    properIrrigation: "योग्य सिंचन",
    cropRotation: "पीक फेरपालट",
    soilTesting: "माती परीक्षण",
    regularInspection: "नियमित तपासणी",
    farmSize: "शेताचा आकार (एकर)",
    cropType: "पिकाचा प्रकार",
    estimateCost: "खर्चाचा अंदाज",
    fungicide: "बुरशीनाशक",
    nutrients: "पोषक पूरक",
    pesticides: "कीटकनाशके",
    totalCost: "एकूण अंदाजित खर्च",
    costNote: "सरासरी बाजार किमतींवर आधारित खर्चाचा अंदाज लावला जातो.",
    lowRisk: "कमी धोका",
    moderateRisk: "मध्यम धोका",
    highRisk: "जास्त धोका",
    healthy: "निरोगी",
    mildInfection: "सौम्य संसर्ग",
    moderateInfection: "मध्यम संसर्ग",
    severeInfection: "गंभीर संसर्ग",
    diseaseDescription: "अगेती अंगमारी हा टोमॅटोच्या पानांना प्रभावित करणारा बुरशी रोग आहे.",
    weatherRiskMsg: "सध्याच्या हवामान परिस्थिती रोगाच्या प्रगतीवर परिणाम करू शकतात.",
    scan: "स्कॅन",
    history: "इतिहास",
    plantGuide: "वनस्पती मार्गदर्शक",
    about: "बद्दल",
    language: "भाषा",
    cropEncyclopedia: "पीक ज्ञानकोश",
    browsecrops: "पिके आणि त्यांचे सामान्य रोग पहा",
    searchCrops: "पिके शोधा...",
    allCrops: "सर्व पिके",
    vegetables: "भाज्या",
    fruits: "फळे",
    grains: "धान्य",
    knownDiseases: "ज्ञात रोग",
    commonDiseases: "सामान्य रोग",
    symptoms: "लक्षणे",
    preventiveActions: "प्रतिबंधात्मक कृती",
    weatherRiskPredictor: "हवामान धोका अंदाजक",
    predictRisk: "धोक्याचा अंदाज",
    diseaseRisk: "रोग धोका",
  },
  bn: {
    analysisResults: "বিশ্লেষণ ফলাফল",
    detailedReport: "বিস্তারিত উদ্ভিদ স্বাস্থ্য প্রতিবেদন",
    diseaseDetected: "রোগ সনাক্ত হয়েছে",
    confidence: "আস্থা",
    severity: "তীব্রতা",
    affectedArea: "আক্রান্ত এলাকা",
    healthScore: "উদ্ভিদ স্বাস্থ্য স্কোর",
    description: "বিবরণ",
    causes: "কারণ",
    treatment: "চিকিৎসা",
    medicine: "ওষুধ",
    prevention: "প্রতিরোধ",
    costEstimator: "খরচ অনুমানকারী",
    weather: "আবহাওয়া ও ঝুঁকি",
    downloadPdf: "PDF রিপোর্ট ডাউনলোড",
    voiceAsk: "ভয়েসে জিজ্ঞাসা করুন",
    voiceListen: "পরামর্শ শুনুন",
    stopVoice: "থামুন",
    speakingAdvice: "বলছে…",
    listeningVoice: "শুনছে…",
    youSaid: "আপনি বলেছেন:",
    fungalInfection: "ছত্রাক সংক্রমণ",
    excessMoisture: "অতিরিক্ত আর্দ্রতা",
    poorSoilNutrients: "দুর্বল মাটির পুষ্টি",
    pestDamage: "পোকামাকড়ের ক্ষতি",
    removeInfectedLeaves: "সংক্রমিত পাতা সরান",
    removeExplanation: "সংক্রমিত পাতা সরানো ছত্রাক ছড়ানো রোধ করে।",
    applyFungicide: "ছত্রাকনাশক স্প্রে করুন",
    fungicideExplanation: "ছত্রাকনাশক একটি প্রতিরক্ষামূলক বাধা তৈরি করে।",
    improveAirCirculation: "বায়ু চলাচল উন্নত করুন",
    airExplanation: "ভালো বায়ু প্রবাহ আর্দ্রতা কমায়।",
    reduceOverwatering: "অতিরিক্ত জল দেওয়া কমান",
    waterExplanation: "অতিরিক্ত জল আর্দ্র পরিস্থিতি তৈরি করে।",
    properIrrigation: "সঠিক সেচ",
    cropRotation: "শস্য ঘূর্ণন",
    soilTesting: "মাটি পরীক্ষা",
    regularInspection: "নিয়মিত পরিদর্শন",
    farmSize: "খামারের আকার (একর)",
    cropType: "ফসলের ধরন",
    estimateCost: "খরচ অনুমান",
    fungicide: "ছত্রাকনাশক",
    nutrients: "পুষ্টি সম্পূরক",
    pesticides: "কীটনাশক",
    totalCost: "মোট আনুমানিক খরচ",
    costNote: "গড় বাজার মূল্যের উপর ভিত্তি করে খরচ অনুমান করা হয়।",
    lowRisk: "কম ঝুঁকি",
    moderateRisk: "মাঝারি ঝুঁকি",
    highRisk: "উচ্চ ঝুঁকি",
    healthy: "সুস্থ",
    mildInfection: "হালকা সংক্রমণ",
    moderateInfection: "মাঝারি সংক্রমণ",
    severeInfection: "গুরুতর সংক্রমণ",
    diseaseDescription: "আর্লি ব্লাইট একটি ছত্রাক রোগ যা টমেটো পাতায় প্রভাব ফেলে।",
    weatherRiskMsg: "বর্তমান আবহাওয়া রোগের অগ্রগতিকে প্রভাবিত করতে পারে।",
    scan: "স্ক্যান",
    history: "ইতিহাস",
    plantGuide: "উদ্ভিদ গাইড",
    about: "সম্পর্কে",
    language: "ভাষা",
    cropEncyclopedia: "ফসল বিশ্বকোষ",
    browsecrops: "ফসল এবং তাদের সাধারণ রোগ ব্রাউজ করুন",
    searchCrops: "ফসল খুঁজুন...",
    allCrops: "সমস্ত ফসল",
    vegetables: "সবজি",
    fruits: "ফল",
    grains: "শস্য",
    knownDiseases: "পরিচিত রোগ",
    commonDiseases: "সাধারণ রোগ",
    symptoms: "লক্ষণ",
    preventiveActions: "প্রতিরোধমূলক পদক্ষেপ",
    weatherRiskPredictor: "আবহাওয়া ঝুঁকি পূর্বাভাস",
    predictRisk: "ঝুঁকি পূর্বাভাস",
    diseaseRisk: "রোগের ঝুঁকি",
  },
};

export const t = (lang: string, key: string): string => {
  return translations[lang]?.[key] || translations.en[key] || key;
};
